# Generated by Django 2.2.1 on 2019-10-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='herois',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('universo', models.CharField(max_length=150, verbose_name='Nome')),
                ('habilidade', models.CharField(max_length=150, verbose_name='Nome')),
            ],
        ),
    ]
